/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.smc.lrtraining.manage.tasks.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Task service. Represents a row in the &quot;MT_Task&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.smc.lrtraining.manage.tasks.model.impl.TaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.smc.lrtraining.manage.tasks.model.impl.TaskImpl}.
 * </p>
 *
 * @author Michele Perissinotto
 * @see Task
 * @see it.smc.lrtraining.manage.tasks.model.impl.TaskImpl
 * @see it.smc.lrtraining.manage.tasks.model.impl.TaskModelImpl
 * @generated
 */
@ProviderType
public interface TaskModel extends BaseModel<Task>, GroupedModel, ShardedModel,
	StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task model instance should use the {@link Task} interface instead.
	 */

	/**
	 * Returns the primary key of this task.
	 *
	 * @return the primary key of this task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task.
	 *
	 * @param primaryKey the primary key of this task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this task.
	 *
	 * @return the uuid of this task
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this task.
	 *
	 * @param uuid the uuid of this task
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the task ID of this task.
	 *
	 * @return the task ID of this task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task.
	 *
	 * @param taskId the task ID of this task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the group ID of this task.
	 *
	 * @return the group ID of this task
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task.
	 *
	 * @param groupId the group ID of this task
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task.
	 *
	 * @return the company ID of this task
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task.
	 *
	 * @param companyId the company ID of this task
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this task.
	 *
	 * @return the user ID of this task
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task.
	 *
	 * @param userId the user ID of this task
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task.
	 *
	 * @return the user uuid of this task
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this task.
	 *
	 * @param userUuid the user uuid of this task
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task.
	 *
	 * @return the user name of this task
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task.
	 *
	 * @param userName the user name of this task
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task.
	 *
	 * @return the create date of this task
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task.
	 *
	 * @param createDate the create date of this task
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task.
	 *
	 * @return the modified date of this task
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task.
	 *
	 * @param modifiedDate the modified date of this task
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this task.
	 *
	 * @return the title of this task
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this task.
	 *
	 * @param title the title of this task
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this task.
	 *
	 * @return the description of this task
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task.
	 *
	 * @param description the description of this task
	 */
	public void setDescription(String description);

	/**
	 * Returns the expiration date of this task.
	 *
	 * @return the expiration date of this task
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this task.
	 *
	 * @param expirationDate the expiration date of this task
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the task user ID of this task.
	 *
	 * @return the task user ID of this task
	 */
	public long getTaskUserId();

	/**
	 * Sets the task user ID of this task.
	 *
	 * @param taskUserId the task user ID of this task
	 */
	public void setTaskUserId(long taskUserId);

	/**
	 * Returns the task user uuid of this task.
	 *
	 * @return the task user uuid of this task
	 */
	public String getTaskUserUuid();

	/**
	 * Sets the task user uuid of this task.
	 *
	 * @param taskUserUuid the task user uuid of this task
	 */
	public void setTaskUserUuid(String taskUserUuid);

	/**
	 * Returns the completed of this task.
	 *
	 * @return the completed of this task
	 */
	public boolean getCompleted();

	/**
	 * Returns <code>true</code> if this task is completed.
	 *
	 * @return <code>true</code> if this task is completed; <code>false</code> otherwise
	 */
	public boolean isCompleted();

	/**
	 * Sets whether this task is completed.
	 *
	 * @param completed the completed of this task
	 */
	public void setCompleted(boolean completed);

	/**
	 * Returns the status of this task.
	 *
	 * @return the status of this task
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this task.
	 *
	 * @param status the status of this task
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this task.
	 *
	 * @return the status by user ID of this task
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this task.
	 *
	 * @param statusByUserId the status by user ID of this task
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this task.
	 *
	 * @return the status by user uuid of this task
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this task.
	 *
	 * @param statusByUserUuid the status by user uuid of this task
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this task.
	 *
	 * @return the status by user name of this task
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this task.
	 *
	 * @param statusByUserName the status by user name of this task
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this task.
	 *
	 * @return the status date of this task
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this task.
	 *
	 * @param statusDate the status date of this task
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this task is approved.
	 *
	 * @return <code>true</code> if this task is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this task is denied.
	 *
	 * @return <code>true</code> if this task is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this task is a draft.
	 *
	 * @return <code>true</code> if this task is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this task is expired.
	 *
	 * @return <code>true</code> if this task is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this task is inactive.
	 *
	 * @return <code>true</code> if this task is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this task is incomplete.
	 *
	 * @return <code>true</code> if this task is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this task is pending.
	 *
	 * @return <code>true</code> if this task is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this task is scheduled.
	 *
	 * @return <code>true</code> if this task is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.smc.lrtraining.manage.tasks.model.Task task);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.smc.lrtraining.manage.tasks.model.Task> toCacheModel();

	@Override
	public it.smc.lrtraining.manage.tasks.model.Task toEscapedModel();

	@Override
	public it.smc.lrtraining.manage.tasks.model.Task toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}